receipt.html modified to comply with afip
WhyNotHugo/django-afip pull request #201
Opened 2023-09-26 16:52 UTC by erebodino

Added:
entries_per_page to PdfBuilder

Modified:

- get_context from PdfBuilder to add create_entries_context_for_render to create a dict to manage multiples pages with subtotal and a list of ReceiptEntry objects
- Refactor test in test_views
- Add test to test the new implementation.

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/templates/receipts/code_6.html
> +    {% for page,value in entries.items %}
`value` is not a very descriptive variable name:

```suggestion
    {% for page, page_entries in entries.items %}
```

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/templates/receipts/code_6.html
> +              {% if llave == 'previous_subtotal' %}
Si mal no recuerdo, deberías poder usar `{{ value.items.previous_subtotal }}` acá.

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/templates/receipts/code_6.html
> +            {% if llave == 'entries' %}
Idem

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/templates/receipts/code_6.html
> +                  {% if llave == 'subtotal' %}
Idem

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/pdf.py
> +def create_entries_context_for_render(paginator: Paginator) -> dict:
```suggestion

from decimal import Decimal
from typing import TypedDict, Sequence


class EntiresForPage(TypedDict):
    previous_subtotal: Decimal
    subtotal: Decimal
    entries: Sequence[Entry]


def create_entries_context_for_render(paginator: Paginator) -> dict[int, EntriesForPage]:
```

2023-09-27 09:26 UTC, WhyNotHugo commented on tests/test_views.py
> +
```suggestion
```

Tengo en mente re-hacer este test usando snapshots más adelante para que este sea menos dolor: https://github.com/WhyNotHugo/django-afip/issues/203

2023-09-27 09:26 UTC, WhyNotHugo commented on django_afip/templates/receipts/code_6.html
> +      <div style="page-break-after: always;" ></div>
Este `div` adicional no hace falta; este estilo podría aplicar a `<div class="receipt">` (del cual existe exactamente uno por página).

2023-09-27 17:09 UTC, erebodino commented
Justo me estaba poniendo a ver el tema de las llaves dentro del diccionario y encontré un problema, el `save_pdf()` es activado por una señal:

```python3
@receiver(post_save, sender=models.ReceiptPDF)
def generate_receipt_pdf(
    sender: type[Model],
    instance: models.ReceiptPDF,
    **kwargs,
) -> None:
    if not instance.pdf_file and instance.receipt.is_validated:
        instance.save_pdf(save_model=True)
```

Lo cual genera un error, ya inicializa el `PdfBuilder` con `entries_per_page=15` como default y después toma el cambio, produciendo 2 PDF distintos, uno con 15 lineas y otro con X lineas. Por instancia no se puede obtener el parametro `entries_per_page` porque no es el modelo.

Mi pregunta es: porque generar la señal para crear un pdf? no seria mejor dejar al usuario que invoque el metodo `save_pdf()` sobre el objeto?

2023-10-03 09:13 UTC, WhyNotHugo commented
Eliminar la señal sería lo menos problemática. Ya de por sí es medio "mágica" y puede que alguien que no esté atento no esté al tanto de que existe.

2023-10-04 15:29 UTC, erebodino commented
> Eliminar la señal sería lo menos problemático. Ya de por sí es medio "mágica" y puede que alguien que no esté atento no esté al tanto de que existe.

Ahí elimine la señal y refactorice algunos tests para subsanar eso (una factory, chequeaba la creación) ahora todo esta corriendo ok.

2023-10-04 21:57 UTC, WhyNotHugo requested changes

2023-10-04 21:57 UTC, WhyNotHugo commented on django_afip/signals.py
> -        instance.save_pdf(save_model=True)
Esto debería estar en el changelog como **BREAKING** para v12.0:

```rst
- **BREAKING**: The signal that auto-generated receipt pdfs for validated
  ReceiptPDFs  has been removed. Applications now need to explicitly call
  :meth:`~.ReceiptPDF.save_pdf()`.
```

2023-10-04 21:57 UTC, WhyNotHugo commented on django_afip/pdf.py
> +    entries: Sequence[Entry]
No hay ningún tipo `Entry`, es `ReceiptEntry`. Y falta el import.

```
> mypy .
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
django_afip/pdf.py:98: error: Name "Entry" is not defined  [name-defined]
django_afip/pdf.py:103: error: Name "EntriesForPage" is not defined  [name-defined]
django_afip/pdf.py:104: error: Need type annotation for "entries" (hint: "entries: Dict[<type>, <type>] = ...")  [var-annotated]
Found 3 errors in 1 file (checked 61 source files)
```

2023-10-04 21:57 UTC, WhyNotHugo commented on django_afip/pdf.py
> +            subtotal += round(entry.total_price, 2)
`round` devuelve un `float`, pero siempre usamos `Decimal` para montos. Hace falta round acá? Hay algúna situación en la cual los tengan más de dos dígitos?

2023-10-04 21:57 UTC, WhyNotHugo commented on django_afip/factories.py
> +    def post(obj: models.ReceiptPDF, create, extracted, **kwargs):
```suggestion
    def post(obj: models.ReceiptPDF, create: bool, extracted: None, **kwargs) -> None:
```

2023-10-04 21:57 UTC, WhyNotHugo commented on tests/test_pdf.py
> +def test_create_entries_for_render():
```suggestion
def test_create_entries_for_render() -> None:
```

2023-10-04 21:57 UTC, WhyNotHugo commented on django_afip/pdf.py
> +from typing import TypedDict
Imports al principio del archivo.

2023-10-04 22:08 UTC, erebodino commented on django_afip/pdf.py
> +            subtotal += round(entry.total_price, 2)
Esto es necesario porque sin el round devuelve un numero con redondeado con 4 decimales, por mas que todos los números sean `DecimalField`

2023-10-04 22:09 UTC, erebodino commented on django_afip/pdf.py
> +from typing import TypedDict
Mala mía, se me paso completamente.

2023-10-04 22:12 UTC, erebodino commented on django_afip/pdf.py
> +    entries: Sequence[Entry]
done

2023-10-04 22:18 UTC, erebodino commented on django_afip/signals.py
> -        instance.save_pdf(save_model=True)
added to the changelog

2023-10-04 22:52 UTC, erebodino commented
ahora es peor el error en mypy, acá hay algo que no entiendo:
>pdf.py:106: error: Missing keys ("previous_subtotal", "subtotal", "entries") for TypedDict "EntriesForPage"  [typeddict-item]
pdf.py:107: error: Value of "previous_subtotal" has incompatible type "int"; expected "Decimal"  [typeddict-item]
pdf.py:112: error: Value of "subtotal" has incompatible type "int"; expected "Decimal"  [typeddict-item]
pdf.py:113: error: Value of "entries" has incompatible type "_SupportsPagination[Any]"; expected "Sequence[Any]"  [typeddict-item]

entonces se tendria que cambiar a:

```python3

class EntriesForPage(TypedDict):
    previous_subtotal: int
    subtotal: int
    entries:  ??
```

pero previous_subtotal y subtotal son `float`. Si los cambio a ìnt` el error desaparece (pero no son int, sino float)

2023-10-05 09:39 UTC, WhyNotHugo commented
`subtotal` se está inicializando con `0` (int), debería ser `Decimal(0)`.

```diff,python
diff --git a/django_afip/pdf.py b/django_afip/pdf.py
index de66dda..1d7d20d 100644
--- a/django_afip/pdf.py
+++ b/django_afip/pdf.py
@@ -3,9 +3,10 @@ from __future__ import annotations
 import base64
 import json
 import logging
+from decimal import Decimal
 from io import BytesIO
 from typing import TYPE_CHECKING
-from typing import Sequence
+from typing import Iterable
 from typing import TypedDict
 
 import qrcode
@@ -13,7 +14,6 @@ from django.core.paginator import Paginator
 from django_renderpdf.helpers import render_pdf
 
 if TYPE_CHECKING:
-    from decimal import Decimal
     from typing import IO
 
     from PIL import Image
@@ -94,23 +94,26 @@ TEMPLATE_NAMES = [
 class EntriesForPage(TypedDict):
     previous_subtotal: Decimal
     subtotal: Decimal
-    entries: Sequence[ReceiptEntry]
+    entries: Iterable[ReceiptEntry]
 
 
 def create_entries_context_for_render(
     paginator: Paginator,
 ) -> dict[int, EntriesForPage]:
     entries: dict[int, EntriesForPage] = {}
-    subtotal = 0
+    subtotal = Decimal(0)
     for i in paginator.page_range:
-        entries[i] = {}
-        entries[i]["previous_subtotal"] = subtotal
+        previous_subtotal = subtotal
         page = paginator.get_page(i)
+
         for entry in page.object_list:
-            subtotal += round(entry.total_price, 2)
+            subtotal += entry.total_price
 
-        entries[i]["subtotal"] = subtotal
-        entries[i]["entries"] = paginator.get_page(i).object_list
+        entries[i] = {
+            "previous_subtotal": previous_subtotal,
+            "subtotal": subtotal,
+            "entries": paginator.get_page(i).object_list,
+        }
     return entries
```

En un ratito aplico estos cambios; creo sería lo único pendiente y el reste está todo okay :+1:

2023-10-05 11:27 UTC, erebodino commented
cuidado con:

> ```diff
> -            subtotal += round(entry.total_price, 2)
> +            subtotal += entry.total_price

Como te mencionaba antes el numero que devuelve es con 4 decimales. En vez de devolver `Subtotal: 10.00` devuelve `subtotal: 10.0000`. [archivo con subtotales incorrectos](https://github.com/WhyNotHugo/django-afip/files/12817736/76219e5054bc42319408916ddd675beb.pdf)
 
No se me ocurre el porque, ya que todos los valores con los que se usa el calculo son con 2 decimales, si bien existe la posibilidad de que en la multiplicación se generan mas decimales, también es necesario redondear a 2 decimales en ese caso.
ejemplo: 

10.00 * 2.00 == 20

pero 15.79 * 3.27 == 51.6333, en este caso si habría que redondear a 2 decimales.

2023-10-06 10:29 UTC, WhyNotHugo commented
Ah, ahí entendí que está pasando. `total_price` devuelve con cuatro decimals:

```pycon
>>> Decimal("2.00") * Decimal("1.00")
Decimal('2.0000')
```

Supongo que es razonable por casos como:

```pycon
>>> Decimal("1.01") * Decimal("1.50")
Decimal('1.5150')
```

Agregué un par de commits, creo que eso debería cubrir bien este tema y todo lo que es type annotations.

2023-10-06 12:30 UTC, merged

2023-10-06 12:31 UTC, WhyNotHugo commented
Thanks!